version: '3.9'

services:
  pgvector:
    image:
    container_name:
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - ""
    volumes:
      - pg
    restart: unless-stopped

  minio:
    image: quay.io
    container_name:
    command:
    environment:
      MINIO_ROOT_USER:
      MINIO_ROOT_PASSWORD:
    ports:
      - ""
      - ""
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
  minio-data:
  pgvector-data: